### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by KrunchMuffin** [idleberg/atom-atomizr#1]
1. Install via APM
2. Run Convert Sublime to Atom

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [atomizr](https://github.com/idleberg/atom-atomizr) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /C:/Users/ICG/.atom/packages/atomizr/lib/atomizr.coffee:108

TypeError: Cannot read property 'getText' of undefined
    at Object.module.exports.Atomizr.sublToAtom (file:///C:/Users/ICG/.atom/packages/atomizr/lib/atomizr.coffee:87:18)
    at atom-workspace.subscriptions.add.atom.commands.add.atomizr:convert-sublime-text-to-atom (file:///C:/Users/ICG/.atom/packages/atomizr/lib/atomizr.coffee:29:104)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ICG\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\ICG\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\ICG\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\ICG\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:03.8.0 atomizr:convert-sublime-text-to-atom (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "ignoredNames": [
      ".idea",
      ".rdsTempFiles",
      ".settings",
      ".project",
      ".sublime-gulp.cache",
      "g2u.sublime-workspace"
    ],
    "projectHome": "c:\\inetpub\\wwwroot\\xxxx",
    "themes": [
      "seti-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atomizr, v0.4.0
language-cfml, v0.11.0
monokai, v0.18.0
seti-icons, v0.4.5
seti-ui, v0.8.1
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by idleberg** [comment]
I'll have to test this on Windows 10 later today. From the error message, this shouldn't be related to file you're trying to convert, but I would still love to have a look at it (or a dummy file that produces the same error).

**Comment by KrunchMuffin** [comment]
so here is the thing, are the files supposed to be somewhere or would running that command bring up a file picker window?

**Comment by idleberg** [comment]
No, using this plugin you can only convert completions opened in Atom. Detection is entirely scope-based. Since this package assigns a new scope to Sublime Text JSON files (the scope is `.source.json.subl`), only supported files (that's only `.sublime-completions`) will be converted into Atom snippets. There are additional check for JSON/CSON validity and whether it's the correct syntax.

If you are looking for batch conversion, have a look at this [Ruby script](https://github.com/idleberg/atomizr).

**Comment by KrunchMuffin** [comment]
so that would have to be a `.sublime-completions` file?

**Comment by idleberg** [comment]
This plugin only converts Sublime Text completions <> Atom snippets. The Ruby script also converts `.sublime-snippet` and `tmBundle`.

**Comment by KrunchMuffin** [comment]
i would have to install Ruby tho I assume? No one has this online?

**Comment by idleberg** [comment]
Yes
