### ISSUE TITLE
Uncaught Callback must be a function

### ISSUE THREAD

**Issue by aminya** [idleberg/atom-atomizr#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0-nightly2 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atomizr](https://github.com/idleberg/atom-atomizr) package 0.23.2

### Stack Trace

Uncaught Callback must be a function

```
At fs.js:137

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.rename (fs.js:571:14)
    at Object.renameFile (/packages/atomizr/lib/atomizr.coffee:613:10)
    at Object.atomToVsCode (/packages/atomizr/lib/atomizr.coffee:172:8)
    at /packages/atomizr/lib/atomizr.coffee:68:110)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom-nightly/app-1.44.0-nightly2/resources/app/static/<embedded>:11:349290)
    at Object.didConfirmSelection (~/AppData/Local/atom-nightly/app-1.44.0-nightly2/resources/app/static/<embedded>:11:699460)
    at SelectListView.confirmSelection (~/AppData/Local/atom-nightly/app-1.44.0-nightly2/resources/app/static/<embedded>:11:874849)
    at SelectListView.didClickItem (~/AppData/Local/atom-nightly/app-1.44.0-nightly2/resources/app/static/<embedded>:11:872791)
    at ListItemView.onclick (~/AppData/Local/atom-nightly/app-1.44.0-nightly2/resources/app/static/<embedded>:11:871781)
    at ListItemView.didClick (~/AppData/Local/atom-nightly/app-1.44.0-nightly2/resources/app/static/<embedded>:11:875869)
```

### Commands

```
     -1:26 command-palette:toggle (input.hidden-input)
     -1:20.4.0 core:select-all (input.hidden-input)
     -1:09.6.0 atomizr:convert-atom-to-visual-studio-code (input.hidden-input)
     -1:03.1.0 intentions:highlight (input.hidden-input)
     -1:02.9.0 core:undo (input.hidden-input)
     -0:54.2.0 tree-view:remove (span.name.icon.json-icon.medium-cyan)
     -0:43.7.0 tree-view:copy (span.name.icon.database-icon.medium-maroon)
     -0:41.4.0 tree-view:paste (span.name.icon.icon-file-directory)
     -0:38.9.0 intentions:highlight (input.hidden-input)
     -0:38.8.0 command-palette:toggle (input.hidden-input)
     -0:35.5.0 atomizr:convert-atom-to-sublime-text (input.hidden-input)
     -0:18.5.0 intentions:highlight (input.hidden-input)
     -0:18.4.0 core:undo (input.hidden-input)
     -0:16.3.0 intentions:highlight (input.hidden-input)
     -0:15.9.0 command-palette:toggle (input.hidden-input)
     -0:08.5.0 atomizr:convert-atom-to-visual-studio-code (input.hidden-input)
```

### Non-Core Packages

```
ascii-hex 0.2.0 
atom-beautify 0.33.4 
atom-commander 0.12.0 
atom-console 0.4.6 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-reverser 3.0.4 
atom-typescript 13.4.4 
atomizr 0.23.2 
auto-fold 0.4.0 
autocomplete 0.47.0 
autocomplete-clang 0.12.1 
autocomplete-en-en 0.2.0 
autocomplete-paths 2.12.2 
build 0.70.0 
busy-signal 2.0.1 
colorful-json 1.1.0 
column-select 1.0.1 
cson-parser 0.1.0 
document-outline 2.1.2 
file-icons 2.1.37 
find-trailing-whitespace 0.1.0 
fold-lines 0.2.2 
git-plus 8.7.1 
git-time-machine 2.1.0 
hey-pane 1.2.0 
highlight-selected 0.16.0 
Hydrogen 2.13.1 
ide-c-cpp 0.1.0 
ide-json 0.2.1 
ide-typescript 0.9.1 
indent-detective 0.4.0 
ink 0.11.7 
intentions 1.1.5 
js2coffee 0.19.1 
json-converter 0.2.4 
julia-client 0.11.3 
juno-plus 0.7.1 
language-ini 1.23.0 
language-julia 0.19.2 
language-matlab 0.2.1 
language-pfm 0.82.0 
language-weave 0.6.5 
latex-completions 0.3.6 
less-than-slash 0.19.0 
linter 2.3.1 
linter-clang 4.1.2 
linter-coffeelint 2.0.28 
linter-cpplint 2.1.0 
linter-eslint 8.5.5 
linter-gcc 0.9.0 
linter-gcc2 0.8.8 
linter-htmlhint 1.6.3 
linter-js-yaml 1.4.6 
linter-julia 0.8.3 
linter-shellcheck 1.6.0 
linter-tslint 1.10.37 
linter-ui-default 1.8.0 
markdown-writer 2.11.9 
open-in-github-app 0.2.6 
open-recent 5.0.0 
pdf-view 0.72.0 
platformio-ide 2.6.0 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.10.0 
preview 0.19.0 
preview-inline 1.5.1 
project-manager 3.3.8 
script 3.25.0 
snippet-generator-plus 0.1.2 
split-diff 1.6.1 
string-encoder 0.2.0 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 0.8.6 
teletype 0.13.4 
tool-bar 1.2.0 
turbo-javascript 1.4.0 
uber-juno 0.3.0 
```

**Comment by idleberg** [comment]
Fixed in v0.23.3
