### ISSUE TITLE
Uncaught ReferenceError: tabTrigger is not defined

### ISSUE THREAD

**Issue by bobdobbalina** [idleberg/atom-atomizr#3]
[Enter steps to reproduce below:]

1. Open ST2 snippet:
~~~~~~~~~~~~~~~~
Snippet contents:
~~~~~~~~~~~~~~~~
<snippet>
  <content><![CDATA[
background-image: url( \$images-path + '${1:image path}' );${0:}
]]></content>
  
  <tabTrigger>bi</tabTrigger>
  
  <scope>source.scss</scope>
</snippet>
~~~~~~~~~~~~~~~~
2. Select "Convert Sublime Text to Atom (snippet)" from Packages/Atomizr

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [atomizr](https://github.com/idleberg/atom-atomizr) package, v0.8.1


### Stack Trace

Uncaught ReferenceError: tabTrigger is not defined

```
At /Users/mike/.atom/packages/atomizr/lib/atomizr.coffee:180

ReferenceError: tabTrigger is not defined
    at Object.module.exports.Atomizr.sublSnipToAtom (/Users/mike/.atom/packages/atomizr/lib/atomizr.coffee:180:21)
    at Object.module.exports.Atomizr.autoConvert (/Users/mike/.atom/packages/atomizr/lib/atomizr.coffee:54:8)
    at atom-workspace.subscriptions.add.atom.commands.add.atomizr:automatic-conversion (/Users/mike/.atom/packages/atomizr/lib/atomizr.coffee:32:96)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -1:18.1.0 atomizr:convert-sublime-text-snippet-to-atom (atom-text-editor.editor.is-focused)
     -0:20.6.0 atomizr:convert-sublime-text-completions-to-atom (atom-text-editor.editor.is-focused)
     -0:00.8.0 atomizr:automatic-conversion (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "themes": [
      "atom-material-ui",
      "predawn-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.20.0
atom-beautify, v0.29.3
atom-material-ui, v1.2.10
atom-ternjs, v0.13.2
atomizr, v0.8.1
editorconfig, v1.3.0
emmet, v2.4.3
file-icons, v1.7.3
highlight-line, v0.11.1
highlight-selected, v0.11.2
jquery-snippets, v11.0.0
language-cshtml, v0.1.1
linter, v1.11.4
linter-elm-make, v0.4.0
linter-htmlhint, v1.1.2
linter-jshint, v2.1.0
linter-jsonlint, v1.2.3
linter-sass-lint, v1.3.1
pigments, v0.26.0
predawn-syntax, v1.0.2
project-manager, v2.9.7
set-syntax, v0.3.0
sublime-panes, v0.2.5
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by idleberg** [comment]
Thanks. Please try `v0.8.2`!

**Comment by idleberg** [comment]
The example snippet will still produce an error since `tabTrigger` is required
