### ISSUE TITLE
Can't convert Sublime Text YAML to Atom

### ISSUE THREAD

**Issue by hacdias** [idleberg/atom-atomizr#5]
I'm trying to convert a `.sublime-syntax` file to Atom and it just says `This doesn't seem to be a valid Sublime Text file. Aborting.`. What am I doing wrong?

**Comment by idleberg** [comment]
Atomizr can only convert `.sublime-completions` and `.sublime-snippet` files. As much as I would love to include conversion of syntax files at some point, I find it's a complex thing to do.

Here's what you can do instead:

1. Install [PackageDev](https://packagecontrol.io/packages/PackageDev) for Sublime Text
2. Convert the syntax file (YAML) to the old format (XML) using the *“Package Dev: Convert (YAML, JSON, Plist) to…”* command
3. Use `apm` to convert the XML, see the [Atom Flight Manual](http://flight-manual.atom.io/hacking-atom/sections/converting-from-textmate/) for details

The last step doesn't always work, since `apm` expects a certain folder structure. [Atomizr](https://github.com/idleberg/atomizr.rb) for the command-line can help you putting them in order and then run the `apm` conversion for you.

**Comment by hacdias** [comment]
I have Property List and JSON options. Is it property list the XML one?

And thanks :smile:

**Comment by idleberg** [comment]
Yes, same thing

**Comment by hacdias** [comment]
Hey! I tried using the command-line tool and I get tis error:

```
c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/lib/atomizr.rb:102:in `read_sublime_xml': undefined method `text' for nil:NilClass (NoMethodError)
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/lib/atomizr.rb:91:in `read_xml'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/lib/atomizr.rb:61:in `block in read_file'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/lib/atomizr.rb:55:in `glob'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/lib/atomizr.rb:55:in `read_file'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/bin/atomizr:127:in `block in <top (required)>'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/bin/atomizr:118:in `each'
        from c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/atomizr-0.18.5/bin/atomizr:118:in `<top (required)>'
        from c:/RailsInstaller/Ruby2.2.0/bin/atomizr:22:in `load'
        from c:/RailsInstaller/Ruby2.2.0/bin/atomizr:22:in `<main>'
```

The content of the file is:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>contexts</key>
	<dict>
		<key>brackets</key>
		<array>
			<dict>
				<key>match</key>
				<string>\s+{$</string>
				<key>push</key>
				<string>nested_block</string>
				<key>scope</key>
				<string>punctuation.definition.bracket.Caddyfile</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\s*}$</string>
				<key>pop</key>
				<true/>
				<key>scope</key>
				<string>punctuation.definition.bracket.Caddyfile</string>
			</dict>
		</array>
		<key>comments</key>
		<array>
			<dict>
				<key>match</key>
				<string>#.*</string>
				<key>scope</key>
				<string>comment.line.Caddyfile</string>
			</dict>
		</array>
		<key>env_placeholders</key>
		<array>
			<dict>
				<key>match</key>
				<string>\{(\$\w+|%\w+%)\}</string>
				<key>scope</key>
				<string>constant.language.Caddyfile</string>
			</dict>
		</array>
		<key>extra_spaces</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>invalid.illegal.extra-spaces.Caddyfile</string>
				</dict>
				<key>match</key>
				<string>\s([ \t]+){$</string>
			</dict>
		</array>
		<key>keys</key>
		<array>
			<dict>
				<key>include</key>
				<string>env_placeholders</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>variable.other.Caddyfile</string>
				</dict>
				<key>match</key>
				<string>({{key}})$</string>
				<key>set</key>
				<string>server_block</string>
			</dict>
			<dict>
				<key>match</key>
				<string>{{key}}</string>
				<key>scope</key>
				<string>variable.other.Caddyfile</string>
			</dict>
			<dict>
				<key>match</key>
				<string>,</string>
				<key>scope</key>
				<string>keyword.operator.logical.Caddyfile</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\s{$</string>
				<key>scope</key>
				<string>punctuation.definition.bracket.Caddyfile</string>
				<key>set</key>
				<string>server_block</string>
			</dict>
		</array>
		<key>main</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>support.function.Caddyfile</string>
					<key>2</key>
					<string>source.Caddyfile</string>
				</dict>
				<key>match</key>
				<string>(^\s*import) (.*)</string>
			</dict>
			<dict>
				<key>include</key>
				<string>keys</string>
			</dict>
		</array>
		<key>nested_block</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>keyword.other.Caddyfile</string>
				</dict>
				<key>match</key>
				<string>{{directive}}</string>
			</dict>
			<dict>
				<key>include</key>
				<string>server_block_common</string>
			</dict>
		</array>
		<key>placeholders</key>
		<array>
			<dict>
				<key>include</key>
				<string>env_placeholders</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\{&gt;?\w+\}</string>
				<key>scope</key>
				<string>constant.language.Caddyfile</string>
			</dict>
		</array>
		<key>prototype</key>
		<array>
			<dict>
				<key>include</key>
				<string>comments</string>
			</dict>
			<dict>
				<key>include</key>
				<string>trailing_spaces</string>
			</dict>
			<dict>
				<key>include</key>
				<string>extra_spaces</string>
			</dict>
		</array>
		<key>server_block</key>
		<array>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<string>support.function.Caddyfile</string>
				</dict>
				<key>match</key>
				<string>{{directive}}</string>
			</dict>
			<dict>
				<key>include</key>
				<string>server_block_common</string>
			</dict>
		</array>
		<key>server_block_common</key>
		<array>
			<dict>
				<key>include</key>
				<string>brackets</string>
			</dict>
			<dict>
				<key>include</key>
				<string>placeholders</string>
			</dict>
			<dict>
				<key>match</key>
				<string>"</string>
				<key>push</key>
				<string>string</string>
			</dict>
		</array>
		<key>string</key>
		<array>
			<dict>
				<key>meta_include_prototype</key>
				<false/>
			</dict>
			<dict>
				<key>meta_scope</key>
				<string>string.quoted.double.Caddyfile</string>
			</dict>
			<dict>
				<key>include</key>
				<string>placeholders</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\\.</string>
				<key>scope</key>
				<string>constant.character.escape.Caddyfile</string>
			</dict>
			<dict>
				<key>match</key>
				<string>"</string>
				<key>pop</key>
				<true/>
			</dict>
		</array>
		<key>trailing_spaces</key>
		<array>
			<dict>
				<key>match</key>
				<string>[ \t]+$</string>
				<key>scope</key>
				<string>invalid.illegal.trailing-spaces.Caddyfile</string>
			</dict>
		</array>
	</dict>
	<key>file_extensions</key>
	<array>
		<string>Caddyfile</string>
	</array>
	<key>name</key>
	<string>Caddyfile</string>
	<key>scope</key>
	<string>source.Caddyfile</string>
	<key>variables</key>
	<dict>
		<key>directive</key>
		<string>^\s*(\w+)\b</string>
		<key>key</key>
		<string>[\w_.:/-]+</string>
	</dict>
</dict>
</plist>
```

**Comment by idleberg** [comment]
Hm, works for me:

```cson
contexts:
  brackets: [
    {
      match: "\\s+{$"
      push: "nested_block"
      scope: "punctuation.definition.bracket.Caddyfile"
    }
    {
      match: "^\\s*}$"
      pop: true
      scope: "punctuation.definition.bracket.Caddyfile"
    }
  ]
  comments: [
    {
      match: "#.*"
      scope: "comment.line.Caddyfile"
    }
  ]
  env_placeholders: [
    {
      match: "\\{(\\$\\w+|%\\w+%)\\}"
      scope: "constant.language.Caddyfile"
    }
  ]
  extra_spaces: [
    {
      captures:
        "1": "invalid.illegal.extra-spaces.Caddyfile"
      match: "\\s([ \\t]+){$"
    }
  ]
  keys: [
    {
      include: "env_placeholders"
    }
    {
      captures:
        "1": "variable.other.Caddyfile"
      match: "({{key}})$"
      set: "server_block"
    }
    {
      match: "{{key}}"
      scope: "variable.other.Caddyfile"
    }
    {
      match: ","
      scope: "keyword.operator.logical.Caddyfile"
    }
    {
      match: "\\s{$"
      scope: "punctuation.definition.bracket.Caddyfile"
      set: "server_block"
    }
  ]
  main: [
    {
      captures:
        "1": "support.function.Caddyfile"
        "2": "source.Caddyfile"
      match: "(^\\s*import) (.*)"
    }
    {
      include: "keys"
    }
  ]
  nested_block: [
    {
      captures:
        "1": "keyword.other.Caddyfile"
      match: "{{directive}}"
    }
    {
      include: "server_block_common"
    }
  ]
  placeholders: [
    {
      include: "env_placeholders"
    }
    {
      match: "\\{>?\\w+\\}"
      scope: "constant.language.Caddyfile"
    }
  ]
  prototype: [
    {
      include: "comments"
    }
    {
      include: "trailing_spaces"
    }
    {
      include: "extra_spaces"
    }
  ]
  server_block: [
    {
      captures:
        "1": "support.function.Caddyfile"
      match: "{{directive}}"
    }
    {
      include: "server_block_common"
    }
  ]
  server_block_common: [
    {
      include: "brackets"
    }
    {
      include: "placeholders"
    }
    {
      match: "\""
      push: "string"
    }
  ]
  string: [
    {
      meta_include_prototype: false
    }
    {
      meta_scope: "string.quoted.double.Caddyfile"
    }
    {
      include: "placeholders"
    }
    {
      match: "\\\\."
      scope: "constant.character.escape.Caddyfile"
    }
    {
      match: "\""
      pop: true
    }
  ]
  trailing_spaces: [
    {
      match: "[ \\t]+$"
      scope: "invalid.illegal.trailing-spaces.Caddyfile"
    }
  ]
file_extensions: [
  "Caddyfile"
]
name: "Caddyfile"
scope: "source.Caddyfile"
variables:
  directive: "^\\s*(\\w+)\\b"
  key: "[\\w_.:/-]+"
```

**Comment by hacdias** [comment]
Ow, thank you :)
